<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Djurspel.Core\Djurspel.Core.csproj" />
    <ProjectReference Include="..\Djurspel.Entities\Djurspel.Entities.csproj" />
    <ProjectReference Include="..\Djurspel.Graphics\Djurspel.Graphics.csproj" />
    <ProjectReference Include="..\Djurspel.World\Djurspel.World.csproj" />
    <ProjectReference Include="..\Djurspel.Gameplay\Djurspel.Gameplay.csproj" />
    <ProjectReference Include="..\Djurspel.Game\Djurspel.Game.csproj" />
  </ItemGroup>
</Project>
